const FETCH_INIT_DATA = 'navigation/FETCH_INIT_DATA';
const FETCH_INIT_DATA_SUCCESS = 'navigation/FETCH_INIT_DATA_SUCCESS';
const FETCH_INIT_DATA_FAIL = 'navigation/FETCH_INIT_DATA_FAIL';

export default {
    FETCH_INIT_DATA, 
    FETCH_INIT_DATA_SUCCESS, 
    FETCH_INIT_DATA_FAIL,
};