const FETCH_PLANNING = 'planning/FETCH_PLANNING';
const FETCH_PLANNING_SUCCESS = 'planning/FETCH_PLANNING_SUCCESS';
const FETCH_PLANNING_FAIL = 'planning/FETCH_PLANNING_FAIL';
const ADD_AFFECTATION = 'planning/ADD_AFFECTATION';
const ADD_AFFECTATION_SUCCESS = 'planning/ADD_AFFECTATION_SUCCESS';
const ADD_AFFECTATION_FAIL = 'planning/ADD_AFFECTATION_FAIL';

export default {
    ADD_AFFECTATION, 
    ADD_AFFECTATION_SUCCESS, 
    ADD_AFFECTATION_FAIL,
    FETCH_PLANNING,
    FETCH_PLANNING_SUCCESS,
    FETCH_PLANNING_FAIL,
};